### ISSUE TITLE
Connection URL Syntax - wie sind die Parameter anzuwenden?

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/ServerStatsDB#1]
Die Configuration
`    url-parameters: "useSSL=false"`
ergibt ein MySQL-Fehler:

> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'redstoneworld'@'localhost' to database 'redstoneworlduseSSL=false

Wie muss die Option angewendet werden?

**Comment by Phoenix616** [comment]
Versuch mal das `?` für den Parameter start direkt mit in den `url-parameters` Wert zu machen.

**Comment by RedstoneFuture** [comment]
Jo, klappt. Danke
